### ISSUE TITLE
大佬您好，github上看到您们写的报名小程序脚本，小程序12.1日起仅vip才能手机密码登陆，您的脚本能类似扫码登陆嘛，冒昧打扰，望您海涵！ 

### ISSUE THREAD

**Issue by minjiezhuzhuxia** [zch050217/Registration-tool-automatic-submission-script#1]
大佬您好，github上看到您们（@void2eye @zch050217 ）写的报名小程序脚本，小程序12.1日起仅vip才能手机密码登陆，您的脚本能类似扫码登陆嘛，冒昧打扰，望您海涵！

**Comment by zch050217** [comment]
功能已实现，请重新clone进行使用，release会稍后更新

**Comment by minjiezhuzhuxia** [comment]
感谢大佬的辛苦付出！respect！ @zch050217 @void2eye
